version: '3.1'

services:
  maria:
    image: mariadb:latest
    container_name: "mariadb-test"
    restart: "always"
    ports:
    - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dbsafer00
      - MYSQL_DATABASE=test
      - MYSQL_USER=wedul_dev
      - MYSQL_PASSWORD=dbsafer00